### ISSUE TITLE
Unexpected next nonce error while deploying a new contract

### ISSUE THREAD

**Issue by gionn** [NomicFoundation/hardhat-ignition#664]
I have a working ignition module composed by 3 contracts which deploy fine on hardhat node and on goerli network.

I was trying to deploy on avax fuji testnet but I am getting:

```
IGN405: The next nonce for 0xf0f...bf1 should be 2, but is 1. Please make sure not to send transactions from 0xf0f...bf1 while running this deployment and try again.
```

It may be related to ~the fact that one of those contract constructor was reverting for a misconfiguration on my side~ RPC cache misbehaving, but such error is quite confusing.

**Comment by zoeyTM** [comment]
This was an issue with us not allowing sufficient time for transactions to propagate to other nodes before checking the mempool. A fix has been pushed and merged (https://github.com/NomicFoundation/hardhat-ignition/pull/667) and will be included in the next release of Ignition (likely this week).

Thanks for the issue! Closing this now as the bug has been resolved.

**Comment by brunoenten** [comment]
As mention in the related issue (https://github.com/NomicFoundation/hardhat-ignition/issues/665), I'm still getting this error on fuji, using the development branch HEAD.

**Comment by kanej** [comment]
> As mentioned in the related issue (#665), I'm still getting this error on fuji, using the development branch HEAD. It doesn't happen every time, so it may just be a matter of number of retries or timeout or something.

Hey @brunoenten, we shipped `v0.13.2` with a bug fix for slow propagation of transactions between a infra providers Ethereum nodes. Could you upgrade and check if you are still seeing this?

**Comment by brunoenten** [comment]
I've used it today and didn't encounter any issue! Well done :)

**Comment by kanej** [comment]
> I've used it today and didn't encounter any issue! Well done :)

Thanks. We really appreciate any bug reports coming out of production deployments. So let us know if you run into other issues in the future.

**Comment by MehmeDBDuran** [comment]
I am experiencing a similar issue with version 0.15.5 on the Amoy test network. grantRole transactions that come right after the contract deployments fail with IGN405: The next nonce for 0x17f... should be 458, but is 459. Waiting a couple of seconds and rerunning the ignition deploy command continues to work without any problems.
